include:
  - path: ./docker-compose.metrics.yml
    env_file: .env

services:
  api:
    container_name: nestjs_boilerplate_api
    build: .
    depends_on:
      - database
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - nestjs_boilerplate_network

  database:
    container_name: nestjs_boilerplate_database
    image: bitnami/postgresql:17
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PORT_NUMBER=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - ${POSTGRES_PORT}
    networks:
      - nestjs_boilerplate_network
    volumes:
      - nestjs_boilerplate_database_volume:/bitnami/postgresql

networks:
  nestjs_boilerplate_network:
    driver: bridge

volumes:
  nestjs_boilerplate_database_volume:
    driver: local