version: "3.8"

services:
  api:
    container_name: nestjs_boilerplate_api
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    networks:
      - nestjs_boilerplate_network

networks:
  nestjs_boilerplate_network:
    driver: bridge